services:
  - type: web
    name: medium-clone-api
    runtime: docker
    dockerfilePath: ./Backend/Dockerfile
    dockerContext: ./Backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: FRONTEND_ORIGIN_REGEX
        sync: false
